config/routes.rb
Rails.application.routes.draw do

  resources :visiteurs

  root "home#show"
  get "gemutile" => 'gemutile#show'
  get "projetweblove" => 'projetweblove#show'

end

app/models/visiteur.rb
class Visiteur < ActiveRecord::Base

  validates_presence_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i


  def subscribe_to_mailchimp testing=false
    return true if (Rails.env.test? && !testing)
    list_id = 'f814ca2f86'

    response = Rails.configuration.mailchimp.lists.subscribe({
                                                                 id: list_id,
                                                                 email: {email: email},
                                                                 double_optin: false,
                                                             })
    response
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/gemutile_controller.rb
class GemutileController < ApplicationController

  def show

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show

  end

end

app/controllers/projetweblove_controller.rb
class ProjetwebloveController < ApplicationController

  def show

  end

end

app/controllers/visiteurs_controller.rb
class VisiteursController < ApplicationController
  before_action :set_visiteur, only: [:show, :edit, :update, :destroy]

  # GET /visiteurs
  # GET /visiteurs.json
  def index
    @visiteurs = Visiteur.all
  end

  # GET /visiteurs/1
  # GET /visiteurs/1.json
  def show
  end

  # GET /visiteurs/new
  def new
    @visiteur = Visiteur.new
  end

  # GET /visiteurs/1/edit
  def edit
  end

  # POST /visiteurs
  # POST /visiteurs.json
  def create
    @visiteur = Visiteur.new(visiteur_params)

    respond_to do |format|
      if @visiteur.save
        format.html { redirect_to @visiteur, notice: 'Visiteur was successfully created.' }
        format.json { render :show, status: :created, location: @visiteur }
      else
        format.html { render :new }
        format.json { render json: @visiteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visiteurs/1
  # PATCH/PUT /visiteurs/1.json
  def update
    respond_to do |format|
      if @visiteur.update(visiteur_params)
        format.html { redirect_to @visiteur, notice: 'Visiteur was successfully updated.' }
        format.json { render :show, status: :ok, location: @visiteur }
      else
        format.html { render :edit }
        format.json { render json: @visiteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visiteurs/1
  # DELETE /visiteurs/1.json
  def destroy
    @visiteur.destroy
    respond_to do |format|
      format.html { redirect_to visiteurs_url, notice: 'Visiteur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visiteur
      @visiteur = Visiteur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visiteur_params
      params.require(:visiteur).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/visiteurs_helper.rb
module VisiteursHelper
end

app/views/gemutile/show.html.erb
<div class="container-fluid">

  <p>
      Gemutiles

      En tout premier : sécuriser son application

      Rajouter  gem

      # pour protéger les credentials : https://github.com/bkeepers/dotenv
      gem 'dotenv-rails', :groups => [:development, :test]

      <strong> explication sur l'utilisation de cette gem</strong>

      puis pour que ce soit qlfjl

    </p>

</div>

app/views/home/show.html.erb
<div class="container-fluid"><p>
  <a href="<%= gemutile_path %>">
<img src="http://lorempixel.com/110/110/cats/2"  class="img-circle" alt="image de chat responsive">
</a>
</p>
    <p>
      <a class="btn btn-primary btn-lg" role="button">Learn more</a>
    </p>

</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for bootstrap 3 %>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" <%= link_to "WebLoveAnd.co", root_url %></a>

    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages statiques <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Projet Web Love", projetweblove_path %></li>
            <li><%= link_to "Gems utiles", gemutile_path %></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'à propos', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path('contact') %></li>
<li><%= link_to 'Historique', page_path('historique') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Backtonew</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap' %>
  <%= stylesheet_link_tag 'bootstrap.map.css' %>
  <%= stylesheet_link_tag 'bootstrap-theme.map.css' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navigation" %>
<%= yield %>

</body>
</html>

app/views/projetweblove/show.html.erb
<div class="container-fluid">
<h1>Pour que la technologie disparaisse au profit de l'usage.</h1>

  <p>

    Etude de faisabilité sur la fabrication d'un logiciel open source d'édition de base de données ET de publication
    web, basé sur une rétro-ingénierie du Logiciel Apple FileMaker Pro (fonctionnement en réseau, simplicité, graphisme,
    multi-langue, etc.), prenant en compte les besoins actuels de publications sur différents supports (intégration
    d'Apache Cordova).

  <ul>
    <li>libre</li>
    <li>européen</li>
    <li>multilingue de part sa création, sa documentation</li>
    <li>Mise en place d'une certification européenne</li>
  </ul>

  <h3>Ce programme doit permettre à chacun et de façon évidente:</h3>
  <ul>
    <li>de traiter des données (Créer, Lire, Mettre à jour, Détruire, Chercher, Trier, Calculer)
    </li>
    <li>d’utiliser un outil graphique pour la mise en page des données,</li>
    <li>de présenter et de publier sur le web des données (texte, chiffres, images, vidéos, musiques) de façon
      extrêmement simple
    </li>
    <li>de savoir de façon sure où sont ses données.</li>
  </ul>

  <blockquote>
    De nombreuses fois, je me suis dit... “Mais c’est pas vrais... Il n’y a personne qui vas proposer la même chose que
    FileMaker mais à destination du web et en open…” Et oui… Il n'existe aucun logiciel similaire à FileMakerPro
  </blockquote>
  <p>
    sous Ubuntu, pourtant le monde libre en a besoin... Visiblement c’est compliqué de faire simple ou alors il y a
    quelque chose de pourris au Royaume du Danemark…
  </p>
  <p>
    Aujourd'hui, un utilisateur lambda, un néophyte à donc l'obligation d'utiliser un ensemble de technologies multiples
    et complexes.
  </p>
  <p>
  <ul>
    <li>PHP avec sql avec ou sans framework (Laravelle,...) +++</li>
    <li> Ruby + postgres + rails + javascript + botstrapp++++</li>
    <li>Java …</li>
  </ul>
  <p>
    Le temps d'apprentissage et de vague maîtrise d'au moins une de ces solutions (pour la majorité des néophytes) est
    au
    minimum d'un an... </p>
  <h2>Solutions existantes</h2>
  <ul>
    <li> Il y a OfficeBase... moche et ne fonctionne pas en réseau naturellement et ne publie pas sur le web...</li>
    <li>Il y a kexi http://www.calligra.org/kexi/ qui ressemble à Acces par sa laideur et son approche.</li>
    <li> http://www.wavemaker.com --> Tourne sur Java --> C'est ce qui se rapproche le plus de ce qu'il faut proposer.
      Racheté
      à VMWare il y a deux ans. Il appartient maintenant à une société indienne. Le code source est sur github.
      https://github.com/cloudjee/wavemaker mais, Il ne fonctionne pas avec le jdk libre.
    </li>
  </ul>

  <h2>Avantages et éléments différenciateurs</h2>
  <ul>
    <li>L’interface graphique</li>
    <li>Le minimum de ligne de code</li>
    <li>Le maximum de web</li>
    <li>Un outil résolument européen et multilingue de part sa création, sa documentation, sa traduction.</li>
    <li>Un outil sur et fiable dans le temps.</li>
  </ul>

  <h2>Qui pourrait appuyer le projet WebLove en France ?</h2>

  <ul>
    <li>Audrey Harris PDG de Soubis</li>
    <li>    Benoît Thieulin Directeur général de l'agence digitale la Netscouade Président du CNNum </li>
    <li>    Brigitte Vallée Directrice de Recherche au CNRS </li>
    <li>    Christine Balagué Vice-présidente du CNNum  </li>
    <li>    Cyril Garcia Directeur de la stratégie Cap Gemini </li>
    <li>    Daniel Kaplan Délégué Général de la Fing  </li>
    <li>    Michel Briand Directeur adjoint de la formation à Télécom Bretagne/Vice-président Brest Métropole </li>
    <li>    Nathalie Andrieux Directrice du numérique du groupe La Poste  </li>
    <li>    Serge Abiteboul Directeur de Recherche à l'INRIA  </li>
    <li>    Sophie Pène Professeur à l'Université Paris Descarte  </li>
    <li>    Valérie Peugeot Chercheuse à Orange Lab, Présidente de Vécam, Vice-présidente du CNNum  </li>
    <li>    des écoles informatiques  </li>
    <li>    des universitaires  </li>
    <li>    des chercheurs  </li>
    <li>    La Région Île de France </li>
    <li>    La Ville de Paris </li>
    <li>    Le Grand Paris  </li>
    <li>    Les agglomérations  </li>
    <li>    Les départements  </li>
    <li>    Le ministère de l'Economie Numérique  </li>
    <li>    Stéphane Distinguin </li>
    <li>    Antoine Torikian  </li>
    <li>    Epitec  </li>
    <li>    Epita </li>
    <li>    Etic  </li>
    <li>  42  </li>
    <li>    Simplon </li>
    <li>    Telecom Paris Tech  </li>
    <li>Mine Telecom...</li>
  </ul>
  <p>  En fonction du résultat de cette étude, Il faudra travailler sur une demande subvention européenne liée à la
    réalisation. Budget estimé de la demande de subvention : 2 million d’euros
  </p>
  <h2>WebLove avec qui en Europe ?</h2>
  <p>

    Il faudra mettre en place les relations nécessaires dans chacun des pays européens.
  </p>
  <ul>
    <li>République fédérale d'Allemagne</li>
    <li>République d'Autriche</li>
    <li>Royaume de Belgique</li>
    <li>République de Bulgarie</li>
    <li>République de Chypre</li>
    <li>République de Croatie</li>
    <li>Royaume du Danemark</li>
    <li>Royaume d'Espagne</li>
    <li>République d'Estonie</li>
    <li>République de Finlande</li>
    <li>République française</li>
    <li>République hellénique</li>
    <li>Hongrie Irlande</li>
    <li>République Italienne</li>
    <li>République de Lettonie</li>
    <li>République de Lituanie</li>
    <li>Grand-Duché de Luxembourg</li>
    <li>République de Malte</li>
    <li>Royaume des Pays-Bas</li>
    <li>République de Pologne</li>
    <li>République portugaise</li>
    <li>République tchèque</li>
    <li>Roumanie</li>
    <li>Royaume-Uni</li>
    <li>République slovaque</li>
    <li>République de Slovénie</li>
    <li>République fédérale d'Allemagne</li>
    <li>République d'Autriche</li>
    <li>Royaume de Belgique</li>
    <li>République de Bulgarie</li>
    <li>République de Chypre</li>
    <li>République de Croatie</li>
    <li>Royaume du Danemark</li>
    <li>Royaume d'Espagne</li>
    <li>République d'Estonie</li>
    <li>République de Finlande</li>
    <li>République française</li>
    <li>République hellénique</li>
    <li>Hongrie Irlande</li>
    <li>République Italienne</li>
    <li>République de Lettonie</li>
    <li>République de Lituanie</li>
    <li>Grand-Duché de Luxembourg</li>
    <li>République de Malte</li>
    <li>Royaume des Pays-Bas</li>
    <li>République de Pologne</li>
    <li>République portugaise</li>
    <li>République tchèque</li>
    <li>Roumanie</li>
    <li>Royaume-Uni</li>
    <li>République slovaque</li>
    <li>République de Slovénie</li>
  </ul>

  <h2>WebLove, c'est possible !!! Le monde en a besoin.</h2>
  <ul>
    <li>Au moins 5 développeurs pointus par pays.</li>
    <li>40 vrais développeurs.</li>
    <li>Une bonne organisation.</li>
    <li>Une très bonne analyse en amont…</li>
    <li>Un budget !</li>
  </ul>

  <h2>On récapitule.</h2>
  <p>C’est un projet de dossier de demande de subvention pour réaliser une étude de faisabilité pour un logiciel open
    source.
  <p>L’objectif de ce logiciel est de proposer la fabrication d'un logiciel libre d'édition de base de données ET de
    publication web, basé sur une retro-ingenerie du Logiciel Apple FileMaker Pro (fonctionnement en réseau, simplicité,
    graphisme, multi-langue, etc.), prenant en compte les besoins actuels de publications sur différents supports
    (intégration d'Apache Cordova)
</div>

app/views/visiteurs/_form.html.erb
<%= form_for(@visiteur) do |f| %>
  <% if @visiteur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visiteur.errors.count, "error") %> prohibited this visiteur from being saved:</h2>

      <ul>
      <% @visiteur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visiteurs/edit.html.erb
<h1>Editing visiteur</h1>

<%= render 'form' %>

<%= link_to 'Show', @visiteur %> |
<%= link_to 'Back', visiteurs_path %>

app/views/visiteurs/index.html.erb
<h1>Listing visiteurs</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visiteurs.each do |visiteur| %>
      <tr>
        <td><%= visiteur.email %></td>
        <td><%= link_to 'Show', visiteur %></td>
        <td><%= link_to 'Edit', edit_visiteur_path(visiteur) %></td>
        <td><%= link_to 'Destroy', visiteur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visiteur', new_visiteur_path %>

app/views/visiteurs/new.html.erb
<h1>New visiteur</h1>

<%= render 'form' %>

<%= link_to 'Back', visiteurs_path %>

app/views/visiteurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @visiteur.email %>
</p>

<%= link_to 'Edit', edit_visiteur_path(@visiteur) %> |
<%= link_to 'Back', visiteurs_path %>